"use client";

import { useEffect, useMemo, useState } from "react";
import { Pencil, RefreshCw, Save, Search, Settings2, UserRoundCheck, X } from "lucide-react";
import AdminShell from "@/components/admin/AdminShell";
import { useAsyncData } from "@/hooks/useAsyncData";
import { assignTable, listTableAttendees, listTables, updateTable, updateTablesBulk } from "@/services/tables";
import type { Attendee, GalaTable } from "@/types/database";

async function load(){const [tables,attendees]=await Promise.all([listTables(),listTableAttendees()]);return{tables,attendees};}
const defaultForm={name:"",capacity:10,zone:"General",status:"Disponible",responsible:"",notes:"",location:"",color:"#C8A14D"};
const seats=(a:Attendee)=>Number(a.seats_reserved ?? (a.companion_name?2:1));

export default function TablesPage(){
 const source=useAsyncData(load,[]);const[selected,setSelected]=useState("");const[query,setQuery]=useState("");const[busy,setBusy]=useState("");const[message,setMessage]=useState("");const[modal,setModal]=useState(false);const[bulkModal,setBulkModal]=useState(false);const[form,setForm]=useState<any>(defaultForm);const[bulkRows,setBulkRows]=useState<GalaTable[]>([]);const[saving,setSaving]=useState(false);
 const tables=source.data?.tables??[];const attendees=source.data?.attendees??[];const active=tables.find(t=>t.id===selected)??tables[0];
 useEffect(()=>setBulkRows(tables.map(t=>({...t}))),[tables]);
 const assigned=useMemo(()=>attendees.filter(a=>a.table_id===active?.id),[attendees,active]);
 const assignedSeats=useMemo(()=>assigned.reduce((n,a)=>n+seats(a),0),[assigned]);
 const unassigned=useMemo(()=>attendees.filter(a=>!a.table_id&&`${a.full_name} ${a.companion_name??""}`.toLowerCase().includes(query.toLowerCase())),[attendees,query]);
 async function move(a:Attendee,t:GalaTable|null){try{setBusy(a.id);setMessage("");await assignTable(a.id,t?.id??null);await source.reload();setMessage(t?`${a.full_name}${a.companion_name?` + ${a.companion_name}`:""} fue asignado a ${t.name} ocupando ${seats(a)} cupo(s).`:`${a.full_name} quedó sin mesa.`);}catch(e){setMessage(e instanceof Error?e.message:"No fue posible actualizar.");}finally{setBusy("");}}
 function openEdit(t:GalaTable){setSelected(t.id);setForm({name:t.name,capacity:t.capacity,zone:t.zone,status:t.status??"Disponible",responsible:t.responsible??"",notes:t.notes??"",location:t.location??"",color:t.color??"#C8A14D"});setModal(true);}
 function openBulkEdit(){setBulkRows(tables.map(t=>({...t})));setBulkModal(true);}
 async function saveTableChanges(){if(!active||!form.name.trim())return;if(Number(form.capacity)<assignedSeats){setMessage(`La capacidad no puede ser menor que los ${assignedSeats} cupos ya asignados.`);return;}setSaving(true);try{await updateTable(active.id,{name:form.name.trim(),capacity:Number(form.capacity),zone:form.zone,status:form.status,responsible:form.responsible.trim()||null,notes:form.notes.trim()||null,location:form.location.trim()||null,color:form.color||"#C8A14D"});setModal(false);await source.reload();setMessage(`La mesa fue actualizada como “${form.name.trim()}”.`);}catch(e){setMessage(e instanceof Error?e.message:"No fue posible guardar la mesa.");}finally{setSaving(false);}}
 async function saveAllTables(){const names=bulkRows.map(t=>t.name.trim().toLowerCase());if(names.find((n,i)=>names.indexOf(n)!==i)){setMessage("No se pueden guardar dos mesas con el mismo nombre.");return;}for(const t of bulkRows){const occupied=attendees.filter(a=>a.table_id===t.id).reduce((n,a)=>n+seats(a),0);if(!t.name.trim()){setMessage(`La Mesa ${t.table_number} debe tener un nombre.`);return;}if(t.capacity<occupied){setMessage(`La capacidad de “${t.name}” no puede ser menor que sus ${occupied} cupos asignados.`);return;}}setSaving(true);try{await updateTablesBulk(bulkRows.map(t=>({id:t.id,name:t.name.trim(),capacity:Number(t.capacity),zone:t.zone,status:t.status??"Disponible",responsible:t.responsible?.trim()||null,notes:t.notes?.trim()||null,location:t.location?.trim()||null,color:t.color||"#C8A14D"})));setBulkModal(false);await source.reload();setMessage("Las 23 mesas fueron actualizadas correctamente.");}catch(e){setMessage(e instanceof Error?e.message:"No fue posible guardar todas las mesas.");}finally{setSaving(false);}}
 const totals={capacity:tables.reduce((n,t)=>n+t.capacity,0),occupied:attendees.filter(a=>a.table_id).reduce((n,a)=>n+seats(a),0)};
 return <AdminShell><main className="adminPage"><section className="pageHeading"><div><p className="adminEyebrow">Mesas personalizables</p><h1>Salón y mesas</h1><p>La ocupación considera al titular, acompañante y reservas de mesa completa.</p></div><div className="tablePageActions"><button className="adminAction" onClick={source.reload}><RefreshCw size={18}/> Actualizar</button><button className="adminAction primary" onClick={openBulkEdit}><Settings2 size={18}/> Editar las 23 mesas</button></div></section>
 <section className="summaryStrip tableSummary"><div><span>Mesas</span><strong>{tables.length}</strong></div><div><span>Capacidad</span><strong>{totals.capacity}</strong></div><div><span>Cupos asignados</span><strong>{totals.occupied}</strong></div><div><span>Disponibles</span><strong>{Math.max(0,totals.capacity-totals.occupied)}</strong></div></section>{message&&<div className="operationMessage">{message}</div>}{source.error&&<div className="dataError">{source.error}</div>}
 <section className="liveFloorWorkspace"><div className="liveFloor"><div className="stage"><span>ESCENARIO PRINCIPAL</span><strong>II GRAN GALA NACIONAL 2026</strong></div><div className="liveTableGrid">{tables.map(t=>{const guests=attendees.filter(a=>a.table_id===t.id);const count=guests.reduce((n,a)=>n+seats(a),0);const pct=Math.min(100,(count/t.capacity)*100);return <button key={t.id} className={`${active?.id===t.id?"active ":""}${count>=t.capacity?"full":pct>=70?"limited":""}`} onClick={()=>setSelected(t.id)} style={{borderTopColor:t.color??"#C8A14D",minHeight:178}}><span>Mesa {t.table_number}</span><strong>{t.name}</strong><small style={{color:"#e7d7ae",fontWeight:700}}>{count} / {t.capacity} cupos</small><i><b style={{width:`${pct}%`,background:t.color??"#C8A14D"}}/></i><span style={{display:"block",marginTop:10,textAlign:"left",color:"#f7f5ee",fontSize:12.5,lineHeight:1.45}}>{guests.slice(0,4).map(a=><span key={a.id} style={{display:"block",overflow:"hidden",textOverflow:"ellipsis"}}>• {a.full_name}{a.companion_name?` + ${a.companion_name}`:""} <small>({seats(a)} cupos)</small></span>)}</span></button>})}</div><div className="floorFooter"><span>Acceso principal</span><span>Recepción y acreditación</span></div></div>
 <aside className="tableInspector" style={{color:"#f7f5ee"}}><div className="tableInspectorHeading"><div style={{minWidth:0}}><p className="panelEyebrow" style={{color:"#d7d0bf"}}>Mesa seleccionada</p><h2 style={{color:"#fff",fontSize:34,margin:"8px 0 0"}}>{active?`Mesa ${active.table_number}`:"Sin mesas"}</h2>{active&&<strong style={{display:"block",color:"#f4ead2",fontSize:18,marginTop:8}}>{active.name}</strong>}</div>{active&&<button className="adminAction compactAction" onClick={()=>openEdit(active)}><Pencil size={16}/> Editar</button>}</div><p style={{color:"#ddd5c4",fontWeight:700}}>{active?.zone} · {assignedSeats}/{active?.capacity??0} cupos</p>
 <div className="assignedGuests">{assigned.map((a,index)=><div key={a.id} style={{display:"grid",gridTemplateColumns:"28px minmax(0,1fr) auto",gap:10,alignItems:"center",padding:"13px 0",borderBottom:"1px solid rgba(255,255,255,.11)"}}><span style={{color:"#c8a14d",fontWeight:800}}>{index+1}</span><span><strong style={{display:"block",color:"#fff"}}>{a.full_name}</strong>{a.companion_name&&<strong style={{display:"block",color:"#f4d98b",marginTop:4}}>↳ Acompañante: {a.companion_name}</strong>}<small style={{display:"block",color:"#bdb6a8",marginTop:3}}>{a.circles?.name??"Sin círculo"} · {seats(a)} cupo(s)</small></span><button disabled={busy===a.id} onClick={()=>move(a,null)} style={{color:"#ff9c8e",fontWeight:800}}>Retirar</button></div>)}{!assigned.length&&<p style={{color:"#bdb6a8",padding:"16px 0"}}>Esta mesa todavía no tiene asistentes asignados.</p>}</div><hr style={{borderColor:"rgba(255,255,255,.13)"}}/><label className="searchBox compact"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar sin mesa..."/></label><div className="unassignedGuests">{unassigned.slice(0,12).map(a=><button key={a.id} disabled={!active||seats(a)>Number(active.available??active.capacity-assignedSeats)||busy===a.id} onClick={()=>active&&move(a,active)}><UserRoundCheck size={16}/><span>{a.full_name}<small>{a.companion_name?`CON ${a.companion_name} · ${seats(a)} CUPOS`:`${a.circles?.name??"Sin círculo"} · ${seats(a)} CUPO`}</small></span></button>)}</div></aside></section>
 {modal&&active&&<div className="modalLayer"><div className="formModal"><div className="modalHeader"><div><p className="adminEyebrow">Mesa {active.table_number}</p><h2>Editar mesa</h2></div><button onClick={()=>setModal(false)}><X/></button></div><div className="formGrid"><label>Nombre visible<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Capacidad<input type="number" min={Math.max(1,assignedSeats)} value={form.capacity} onChange={e=>setForm({...form,capacity:Number(e.target.value)})}/></label><label>Zona<select value={form.zone} onChange={e=>setForm({...form,zone:e.target.value})}><option>Protocolar</option><option>Autoridades</option><option>Central</option><option>General</option><option>Reserva</option></select></label><label>Estado<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Disponible</option><option>Reservada</option><option>Cerrada</option></select></label><label>Color<input type="color" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></label><label>Ubicación<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Responsable<input value={form.responsible} onChange={e=>setForm({...form,responsible:e.target.value})}/></label><label className="fullField">Observaciones<textarea rows={4} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="modalActions"><button className="adminAction" onClick={()=>setModal(false)}>Cancelar</button><button className="adminAction primary" disabled={saving} onClick={saveTableChanges}>{saving?"Guardando…":"Guardar cambios"}</button></div></div></div>}
 {bulkModal&&<div className="modalLayer bulkTableLayer"><div className="formModal bulkTableModal"><div className="modalHeader"><div><p className="adminEyebrow">Edición general</p><h2>Editar las 23 mesas</h2></div><button onClick={()=>setBulkModal(false)}><X/></button></div><div className="bulkTableEditor"><div className="bulkTableHeader"><span>Nº</span><span>Nombre visible</span><span>Capacidad</span><span>Zona</span><span>Estado</span><span>Color</span></div>{bulkRows.map((t,i)=><div className="bulkTableRow" key={t.id}><strong>{t.table_number}</strong><input value={t.name} onChange={e=>setBulkRows(r=>r.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/><input type="number" min="1" value={t.capacity} onChange={e=>setBulkRows(r=>r.map((x,j)=>j===i?{...x,capacity:Number(e.target.value)}:x))}/><select value={t.zone} onChange={e=>setBulkRows(r=>r.map((x,j)=>j===i?{...x,zone:e.target.value as GalaTable["zone"]}:x))}><option>Protocolar</option><option>Autoridades</option><option>Central</option><option>General</option><option>Reserva</option></select><select value={t.status??"Disponible"} onChange={e=>setBulkRows(r=>r.map((x,j)=>j===i?{...x,status:e.target.value as GalaTable["status"]}:x))}><option>Disponible</option><option>Reservada</option><option>Cerrada</option></select><input type="color" value={t.color??"#C8A14D"} onChange={e=>setBulkRows(r=>r.map((x,j)=>j===i?{...x,color:e.target.value}:x))}/></div>)}</div><div className="modalActions stickyActions"><button className="adminAction" onClick={()=>setBulkModal(false)}>Cancelar</button><button className="adminAction primary" disabled={saving} onClick={saveAllTables}><Save size={17}/>{saving?"Guardando…":"Guardar las 23 mesas"}</button></div></div></div>}
 </main></AdminShell>;
}
